# Utilisation de l'image openjdk
FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY target/*.jar complete.jar
EXPOSE 8082
ENTRYPOINT exec java $JAVA_OPTS -jar complete.jar